// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20191030000806_CriarBanco")]
    partial class CriarBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Cliente", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CriadoEm");

                    b.Property<string>("Nome");

                    b.HasKey("PessoaId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Domain.Funcionario", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cargo");

                    b.Property<DateTime>("CriadoEm");

                    b.Property<string>("Login");

                    b.Property<string>("Nome");

                    b.Property<string>("Senha");

                    b.HasKey("PessoaId");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("Domain.Projeto", b =>
                {
                    b.Property<int>("ProjetoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CriadoEm");

                    b.Property<string>("Nome");

                    b.Property<string>("Status");

                    b.Property<int?>("clientePessoaId");

                    b.HasKey("ProjetoId");

                    b.HasIndex("clientePessoaId");

                    b.ToTable("Projeto");
                });

            modelBuilder.Entity("Domain.Tarefa", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssinaturaPessoaId");

                    b.Property<DateTime>("CriadoEm");

                    b.Property<string>("Descricao");

                    b.Property<string>("Prioridade");

                    b.Property<int?>("ProjetoId");

                    b.Property<int?>("RequisitantePessoaId");

                    b.Property<string>("Resolucao");

                    b.Property<string>("Status");

                    b.Property<string>("Tipo");

                    b.Property<string>("Titulo");

                    b.HasKey("TarefaId");

                    b.HasIndex("AssinaturaPessoaId");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("RequisitantePessoaId");

                    b.ToTable("Tarefa");
                });

            modelBuilder.Entity("Domain.Projeto", b =>
                {
                    b.HasOne("Domain.Cliente", "cliente")
                        .WithMany()
                        .HasForeignKey("clientePessoaId");
                });

            modelBuilder.Entity("Domain.Tarefa", b =>
                {
                    b.HasOne("Domain.Funcionario", "Assinatura")
                        .WithMany()
                        .HasForeignKey("AssinaturaPessoaId");

                    b.HasOne("Domain.Projeto", "Projeto")
                        .WithMany()
                        .HasForeignKey("ProjetoId");

                    b.HasOne("Domain.Funcionario", "Requisitante")
                        .WithMany()
                        .HasForeignKey("RequisitantePessoaId");
                });
#pragma warning restore 612, 618
        }
    }
}
